### ISSUE TITLE
Baixar todos os datasets

### ISSUE THREAD

**Issue by alvarofpp** [odufrn/odufrn-downloader#17]
# Função
Baixar todos os conjuntos de dados disponíveis. Seria um método pouquíssimo utilizado, porém ajudaria muito quem fosse fazer isso.

## Para entender melhor
Digamos que você queira baixar todos os dados, sem o dicionário e de 2013 a 2018. Para isso você deveria pegar uma lista enorme de _datasets_ e inserir no `download_datasets`, sendo que poderia ser:

```python
from odufrn_downloader import ODUFRNDownloader
ufrn_data = ODUFRNDownloader()

# Baixar todos os datasets, sem dicionário e de 2013 a 2018
ufrn_data.download_all(dictionary=False, years=list(range(2013:2019)))
```

**Observações**: Perceba que não é tão diferente do método `download_packages`, pois a entrada seria apenas uma lista de _datasets_, por a que está presente na variável `self.available_datasets`.

**Comment by diegodiogenes** [comment]
### Problema: 

Quando estava implementando o que pede na issue, percebi que o método download_all ficaria muito parecido com o já existente download_datasets:

#### Método download_all

```python
def download_all(self, path: str = os.getcwd(), dictionary: bool = True, years: list = None):
    for dataset in self.available_datasets:
        self.download_dataset(dataset, path) 
```

#### Método download_datasets

```python
def download_datasets(self, datasets: list, path: str = os.getcwd(), dictionary: bool = True, years: list = None):
    for dataset in datasets:
        self.download_dataset(dataset, path, dictionary, years)
```
### Sugestão:

Poderíamos utilizar o método download_datasets para baixar todos os datasets, onde por default, o método receberia todos os datasets para download. Exemplo:

```python
def download_datasets(self, datasets: list = self.available_datasets, path: str = os.getcwd(), dictionary: bool = True, years: list = None):
    for dataset in datasets:
        self.download_dataset(dataset, path, dictionary, years)
```

O que acham? @itepifanio @alvarofpp @nymarya

**Comment by nymarya** [comment]
> ### Problema:
> Quando estava implementando o que pede na issue, percebi que o método download_all ficaria muito parecido com o já existente download_datasets:
> 
> #### Método download_all
> ```python
> def download_all(self, path: str = os.getcwd(), dictionary: bool = True, years: list = None):
>     for dataset in self.available_datasets:
>         self.download_dataset(dataset, path) 
> ```
> 
> #### Método download_datasets
> ```python
> def download_datasets(self, datasets: list, path: str = os.getcwd(), dictionary: bool = True, years: list = None):
>     for dataset in datasets:
>         self.download_dataset(dataset, path, dictionary, years)
> ```
> 
> ### Sugestão:
> Poderíamos utilizar o método download_datasets para baixar todos os datasets, onde por default, o método receberia todos os datasets para download. Exemplo:
> 
> ```python
> def download_datasets(self, datasets: list = self.available_datasets, path: str = os.getcwd(), dictionary: bool = True, years: list = None):
>     for dataset in datasets:
>         self.download_dataset(dataset, path, dictionary, years)
> ```
> 
> O que acham? @itepifanio @alvarofpp @nymarya

Acho que é uma boa. Evita bastante repetição

**Comment by alvarofpp** [comment]
> ### Sugestão:
> 
> Poderíamos utilizar o método download_datasets para baixar todos os datasets, onde por default, o método receberia todos os datasets para download. Exemplo:
> 
> ```python
> def download_datasets(self, datasets: list = self.available_datasets, path: str = os.getcwd(), dictionary: bool = True, years: list = None):
>     for dataset in datasets:
>         self.download_dataset(dataset, path, dictionary, years)
> ```

Acho válido, porém não creio que seria bom, pois poderia fazer com que o desenvolvedor pensasse que o método `download_dataset` também teria um valor _default_ para o método, como tem para o `download_datasets`.
