### ISSUE TITLE
Baixar datasets com base em tag

### ISSUE THREAD

**Issue by nymarya** [odufrn/odufrn-downloader#25]
## Função

Cria uma função que com base em uma tag, conforme a listagem da [api de dados da UFRN](http://dados.ufrn.br/dataset?tags=cursos).

## Para entender melhor

Com a issue #14 implementada, ainda podem ficar de fora datasets relacionados a um determinado assunto que não possuem a palavra de interesse.

Por exemplo, para procurar datasets relacionados a `graduação`, pela issue #14 seriam listados os seguintes conjuntos:
1. **cursos-de-graduacao**;
2.  **cursos-de-pos-graduacao**;
3. **programas-de-pos-graduacao**;

Por outro lado, quando buscamos por uma etiqueta no site da [API da UFRN](http://dados.ufrn.br/dataset?tags=gradua%C3%A7%C3%A3o), são listados:
1. **discentes**;
2. **cursos-de-graducao**;
3. **turmas**;
4. **cursos-da-ufrn**;
5. **estruturas-curriculares**;

## Exemplo

Sugestão: adicionar parâmetro na função da issue #14 para trazer também datasets relacionados à palavra-chave (tag).

```python
from odufrn_downloader import ODUFRNDownloader
ufrn_data = ODUFRNDownloader()

# Baixar os datasets relacionados a graduacao
ufrn_data.download_related_datasets('graduacao', search_tag=True)
```
O esperado seria `['cursos-de-graduacao', 'cursos-de-pos-graduacao', 'programas-de-pos-graduacao', 'discentes', turmas', 'cursos-da-ufrn', 'estruturas-curriculares']` serem baixados.

```python
# Baixar os datasets relacionados a tag
ufrn_data.download_datasets_by_tag('graduacao') 
```

O esperado seria `['cursos-de-graduacao',  'discentes', turmas', 'cursos-da-ufrn', 'estruturas-curriculares']` serem baixados.

**Comment by CefasR** [comment]
Gente, talvez seja interessante possibilitar download pesquisando em uma lista de tags.

**Comment by nymarya** [comment]
> Gente, talvez seja interessante possibilitar download pesquisando em uma lista de tags.

@alvarofpp @itepifanio @diegodiogenes Acho que dá pra abrir outra issue, e vcs?
