### ISSUE TITLE
Completar o Community.md

### ISSUE THREAD

**Issue by itepifanio** [odufrn/odufrn-downloader#34]
## Feature
Completar todos os pontos restantes da checklist de [Community](https://github.com/odufrn/odufrn-downloader/community) e revisar os pontos já feitos.

Os pontos que faltam:
- [ ] Code of conduct
- [ ] Contributing
  - Criar o arquivo descrevendo como contribuir. Descrever como instalar o pacote para desenvolvimento, como abrir issues e descrever como deve ser a nomenclatura das issues.
  - Lembrar de adicionar um cabeçalho no readme para mostrar que existe a seção de contribuição.
- [ ] Pull request template

**Comment by alvarofpp** [comment]
Colocar _issue_ no projeto **.gitignore** para ser global.
