### ISSUE TITLE
Como filtrar os datasets

### ISSUE THREAD

**Issue by alvarofpp** [odufrn/odufrn-downloader#35]
# Debate
Estava realizando um teste sobre filtrar os _datasets_ e foi o seguinte:
```python
list_discentes = ufrn_data.search_related_datasets('discen')
print(list_discentes)

# Output:
# Não há nenhum conjunto de dados semelhante a "discen".
# []
```

Esse não era o resultado esperado, pois eu poderia desconhecer como se dar a nomenclatura dos _datasets_. Já no segundo teste, o resultado foi o esperado:
```python
list_discentes = ufrn_data.search_related_datasets('discent')
print(list_discentes)

# Output:
# ['dados-complementares-de-discentes', 'dados-socio-economicos-de-discentes', 'discentes']
```

Isso se dá porque o cálculo de similaridade dar "match" quando é acima de 0.87. Portanto, todo o comportamento é esperado, porém, como usuário do pacote, não tenho a obrigação de saber desse "match".

# Sugestão
Poderia ter a possibilidade de a similaridade ser de uma forma mais simples, como apenas um `keyword in dataset_name`, pois aí o comportamento do primeiro teste poderia ser o esperado. Portanto, poderia ter uma flag que diga quando a similaridade deve ser pelo cálculo de Levenshtein ou cálculo simples.

**Comment by nymarya** [comment]
No caso da similaridade maior que 0.87, ele consegue ignorar"typos", por exemplo, se alguém digitar "dicentes". Acho que o melhor seria combinar as duas soluções: verificar se a `keyword in dataset_name` OU `ratio > 0.87`

**Comment by alvarofpp** [comment]
> 
> 
> No caso da similaridade maior que 0.87, ele consegue ignorar"typos", por exemplo, se alguém digitar "dicentes". Acho que o melhor seria combinar as duas soluções: verificar se a `keyword in dataset_name` OU `ratio > 0.87`

Também acho que esse seria o melhor caminho. Dá a possibilidade do programador trabalhar da forma com que achar melhor. Por padrão poderia ser `ratio > 0.87`, ai a flag poderia ser `simple_filter=False`, quando setado como `simple_filter=True`, aplica o filtro `keyword in dataset_name`.

**Comment by diegodiogenes** [comment]
> > No caso da similaridade maior que 0.87, ele consegue ignorar"typos", por exemplo, se alguém digitar "dicentes". Acho que o melhor seria combinar as duas soluções: verificar se a `keyword in dataset_name` OU `ratio > 0.87`
> 
> Também acho que esse seria o melhor caminho. Dá a possibilidade do programador trabalhar da forma com que achar melhor. Por padrão poderia ser `ratio > 0.87`, ai a flag poderia ser `simple_filter=False`, quando setado como `simple_filter=True`, aplica o filtro `keyword in dataset_name`.

Acho que essa é a melhor solução mesmo, por default deixa o ratio > 0.87 e se o usuário não lembrar direito o nome do pacote, seta a flag.
