### ISSUE TITLE
Flag years em outros métodos

### ISSUE THREAD

**Issue by alvarofpp** [odufrn/odufrn-downloader#41]
# Debate
Estava observando os métodos durante um pequeno processo de refatoração e notei que os seguintes métodos não possuem a flag `years`:
- `download_group`
- `download_groups`

Como eles por debaixo chamam a função `download_dataset` e esse método possui a flag `years`, pensei que seria interessante adicionar essa mesma flag a esses métodos. O que acham?

## Para entender melhor
Os casos para qual a flag `years` foi pensada.

**Comment by itepifanio** [comment]
Quando implementei isso eu pensei em adicionar lá também, mas achei que talvez fosse um filtro exagerado, porém é mais uma ferramenta para o desenvolvedor então pode sim ser válido.

**Comment by diegodiogenes** [comment]
Acho bastante válido, deveria ter sido implementado junto com o download_dataset, esquecemos.
