### ISSUE TITLE
Criar classes de exception

### ISSUE THREAD

**Issue by itepifanio** [odufrn/odufrn-downloader#56]
# Feature

Hoje tratamos as exceptions de forma bem geral, porém poderíamos criar classes de exceção para nos auxiliarmos a lidar com os erros. Isso ajuda bastante nos testes, tornando-os mais assertivos, visto que o unittest tem a função ` assertRaises() `

> #### Participe do Hacktoberfest!
> Contribua com uma issue com a label `hacktoberfest` e abra um pull request durante o mês de outubro para ganhar os brindes do GitHub! Para se inscrever, acesse https://hacktoberfest.digitalocean.com/register

**Comment by Physsix27** [comment]
Me puedes dar un pouito mas de explicacion de lo que necesitas? Puedo ayudar agregar mas `unittest` solamente necitatere que me encamines a los files que lo necesitan

**Comment by itepifanio** [comment]
Hola, @Physsix27 

No enumeramos todas las exceptions queremos escribir, pero tenemos un ejemplo. En el [test_file](https://github.com/odufrn/odufrn-downloader/blob/master/tests/test_file.py) tenemos la function ` test_can_print_exception_download_packages_from_file ` pero no tenemos esta exception, solo printamos como ` self._print_exception(ex) ` en la [class File](https://github.com/odufrn/odufrn-downloader/blob/2f0da9c2abd8bdf348231d1c3cb11dea07020fcb/odufrn_downloader/modules/File.py) se tenemos la custom exception podriamos escribir ` raise CustomException ` y entonces ir a los tests y escribir ` assertRaises(CustomException) ` 
Si tu puderes escribir una exception initial como esta descrita, entonces ayudaría mucho.

**Comment by Physsix27** [comment]
Ok, deja ver si entiendo, quieres que escriba un custom `CustonException` pata poder usarla en `self._print_exception(CustonException)` y luego poder usarla en el test? si eso es lo que quieres puedo ayudar.

_**Mi Idioma:**_ Espanol

**Comment by Physsix27** [comment]
Puedes darme una descripcion de lo que hara el `custonexception` cuando tenga esa description puedo poner el PR. ya casi termino

**Comment by Physsix27** [comment]
Hey @itepifanio dejame saber si necesito cambiar algo de mi PR para poder darle `merged`. Ya esta completo.

PR #95
