### ISSUE TITLE
Baixar dicionário de dados quando define range de anos

### ISSUE THREAD

**Issue by diegodiogenes** [odufrn/odufrn-downloader#57]
# Função

Ajustar o método download_package para baixar o dicionário de dados mesmo quando é definido um range para a flag years.

## Para entender melhor

Atualmente, quando a flag years é utilizada, não é baixado o dicionário de dados, que é setado para download por default.

## Debate

Qual seria a melhor forma para resolver esse problema? Porque atualmente o código que faz a distinção dos anos para serem baixados é utilizando um mixin, que verifica o nome do pacote de dados. Teríamos que alterar no mixin a verificação que é feita.

### Atualmente: 

```python
# Package.py
for resource in response['resources']:
                year_find = self.year_find(resource['name'], years)

                if not dictionary and 'Dicion' in resource['name']:
                    continue

                if years is None or year_find:
                    print("Baixando {}...".format(resource['name']))
                    file_path = '{}/{}.{}'.format(
                        path, resource['name'], resource['format'].lower()
                    )
```

```python
# YearsMixin.py
class YearsMixin:
    """ Mixin que adiciona métodos relacionados a filtragem
    de pacotes e grupos por anos"""

    def year_find(self, package_name: str, years: list) -> bool:
        """Verifica se o pacote pertence a uma ano específico da lista years.

        Parâmetros
        ----------
        package_name: str
            nome do pacote a ser filtrado.
        years: list
            anos que serão filtrados na pesquisa.

        Retorno
        ----------
        bool
            True se o ano foi encontrado no nome do pacote se não false."""
        if years is None:
            return True

        year_find = False
        if years:
            for _, year in enumerate(years):
                if str(year) in package_name:
                    year_find = True
        return year_find
```
Inicialmente pensei em colocar a verificação do dicionário também no `YearsMixin`, porém iria ficar repetitivo. Então poderíamos alterar o código que verifica se a flag dicionário está como true dentro do condicional que verifica se foi encontrado o ano no nome do arquivo ou se a flag years é none. O que acham?

@alvarofpp @nymarya @itepifanio

**Comment by alvarofpp** [comment]
Seria interessante termos algo para sabermos qual o tipo de arquivo que está sendo baixado, para só então fazer o filtro. Tipo, realmente não faz sentido vermos se o dicionário de anos está no range de years que foi passado.

**Comment by alvarofpp** [comment]
> Seria interessante termos algo para sabermos qual o tipo de arquivo que está sendo baixado, para só então fazer o filtro. Tipo, realmente não faz sentido vermos se o dicionário de anos está no range de years que foi passado.

Logo, teríamos algo para classificar o arquivo baixado antes de realizar o filtro para download.
