### ISSUE TITLE
Pacote não aparece corretamente no pip freeze

### ISSUE THREAD

**Issue by JohnAzedo** [odufrn/odufrn-downloader#68]
# Debate
Após instalar o pacote utilizando o comando `pip install odufrn-downloader`, e executar o comando `pip freeze` isso aparece:

![Screen Shot 2019-08-19 at 12 44 03](https://user-images.githubusercontent.com/19677206/63281934-21cc0080-c284-11e9-9cd5-d7027fedfe37.png)

O certo seria mostrar odufrn-downloader==1.0.0 mas está aparecendo:
```
# Editable install with no version control (odufrn-downloader==1.0.0)
-e /Users/johnazedo/Documents/.python/lib/python3.7/site-packages
```

**Comment by nymarya** [comment]
@JohnAzedo provavelmente você utilizou o comando `pip install -e .` e o pip interpretou o -e como um pacote.

Instalei o pacote normal no colab e ele apareceu corretamente no `pip freeze`
![image](https://user-images.githubusercontent.com/23341788/63284611-517e0700-c28a-11e9-85aa-fafc2fc8cf9d.png)

**Comment by JohnAzedo** [comment]
Ok, então o problema é só na minha máquina. Vou fechar a issue
